/**
 * The full Madden 27 playbook inventory as observed on Civil.GG (public database,
 * D106/D111 owner-authorized reuse), crawled 2026-10-06 from
 * https://www.civil.gg/playbooks/madden. Counts are what the source published;
 * "loaded" describes whether this site's formation catalog contains the book,
 * never that every play or mapping is verified (C3B expands coverage honestly).
 */

import type { PlaybookRef } from "./types";

const team = (
  id: string,
  side: "offense" | "defense",
  teamLabel: string,
  label: string,
  totalPlays: number,
): PlaybookRef => ({
  id,
  side,
  kind: "team",
  teamLabel,
  label,
  totalPlays,
  civilPath: `/playbooks/team/nfl/${side}/${id.replace(/^nfl-(off|def)-/, "")}`,
});

const alternate = (
  id: string,
  side: "offense" | "defense",
  label: string,
  totalPlays: number,
): PlaybookRef => ({
  id,
  side,
  kind: "alternate",
  teamLabel: side === "offense" ? "Offense" : "Defense",
  label,
  totalPlays,
  civilPath: `/playbooks/team/nfl/${side}/${id.replace(/^alt-(off|def)-/, "")}`,
});

export const PLAYBOOK_INVENTORY: PlaybookRef[] = [
  // Team offensive playbooks (32)
  team("nfl-off-49ers", "offense", "San Francisco", "49ers", 582),
  team("nfl-off-bears", "offense", "Chicago", "Bears", 588),
  team("nfl-off-bengals", "offense", "Cincinnati", "Bengals", 606),
  team("nfl-off-bills", "offense", "Buffalo", "Bills", 589),
  team("nfl-off-broncos", "offense", "Denver", "Broncos", 552),
  team("nfl-off-browns", "offense", "Cleveland", "Browns", 575),
  team("nfl-off-buccaneers", "offense", "Tampa Bay", "Buccaneers", 597),
  team("nfl-off-cardinals", "offense", "Arizona", "Cardinals", 603),
  team("nfl-off-chargers", "offense", "Los Angeles", "Chargers", 577),
  team("nfl-off-chiefs", "offense", "Kansas City", "Chiefs", 579),
  team("nfl-off-colts", "offense", "Indianapolis", "Colts", 591),
  team("nfl-off-commanders", "offense", "Washington", "Commanders", 615),
  team("nfl-off-cowboys", "offense", "Dallas", "Cowboys", 593),
  team("nfl-off-dolphins", "offense", "Miami", "Dolphins", 585),
  team("nfl-off-eagles", "offense", "Philadelphia", "Eagles", 619),
  team("nfl-off-falcons", "offense", "Atlanta", "Falcons", 606),
  team("nfl-off-giants", "offense", "New York", "Giants", 588),
  team("nfl-off-jaguars", "offense", "Jacksonville", "Jaguars", 588),
  team("nfl-off-jets", "offense", "New York", "Jets", 570),
  team("nfl-off-lions", "offense", "Detroit", "Lions", 555),
  team("nfl-off-packers", "offense", "Green Bay", "Packers", 601),
  team("nfl-off-panthers", "offense", "Carolina", "Panthers", 564),
  team("nfl-off-patriots", "offense", "New England", "Patriots", 610),
  team("nfl-off-raiders", "offense", "Las Vegas", "Raiders", 591),
  team("nfl-off-rams", "offense", "Los Angeles", "Rams", 599),
  team("nfl-off-ravens", "offense", "Baltimore", "Ravens", 582),
  team("nfl-off-saints", "offense", "New Orleans", "Saints", 594),
  team("nfl-off-seahawks", "offense", "Seattle", "Seahawks", 571),
  team("nfl-off-steelers", "offense", "Pittsburgh", "Steelers", 577),
  team("nfl-off-texans", "offense", "Houston", "Texans", 579),
  team("nfl-off-titans", "offense", "Tennessee", "Titans", 597),
  team("nfl-off-vikings", "offense", "Minnesota", "Vikings", 600),
  // Team defensive playbooks (32)
  team("nfl-def-49ers", "defense", "San Francisco", "49ers", 316),
  team("nfl-def-bears", "defense", "Chicago", "Bears", 284),
  team("nfl-def-bengals", "defense", "Cincinnati", "Bengals", 252),
  team("nfl-def-bills", "defense", "Buffalo", "Bills", 339),
  team("nfl-def-broncos", "defense", "Denver", "Broncos", 339),
  team("nfl-def-browns", "defense", "Cleveland", "Browns", 263),
  team("nfl-def-buccaneers", "defense", "Tampa Bay", "Buccaneers", 318),
  team("nfl-def-cardinals", "defense", "Arizona", "Cardinals", 363),
  team("nfl-def-chargers", "defense", "Los Angeles", "Chargers", 351),
  team("nfl-def-chiefs", "defense", "Kansas City", "Chiefs", 366),
  team("nfl-def-colts", "defense", "Indianapolis", "Colts", 312),
  team("nfl-def-commanders", "defense", "Washington", "Commanders", 422),
  team("nfl-def-cowboys", "defense", "Dallas", "Cowboys", 360),
  team("nfl-def-dolphins", "defense", "Miami", "Dolphins", 294),
  team("nfl-def-eagles", "defense", "Philadelphia", "Eagles", 360),
  team("nfl-def-falcons", "defense", "Atlanta", "Falcons", 283),
  team("nfl-def-giants", "defense", "New York", "Giants", 378),
  team("nfl-def-jaguars", "defense", "Jacksonville", "Jaguars", 281),
  team("nfl-def-jets", "defense", "New York", "Jets", 324),
  team("nfl-def-lions", "defense", "Detroit", "Lions", 279),
  team("nfl-def-packers", "defense", "Green Bay", "Packers", 363),
  team("nfl-def-panthers", "defense", "Carolina", "Panthers", 381),
  team("nfl-def-patriots", "defense", "New England", "Patriots", 318),
  team("nfl-def-raiders", "defense", "Las Vegas", "Raiders", 315),
  team("nfl-def-rams", "defense", "Los Angeles", "Rams", 309),
  team("nfl-def-ravens", "defense", "Baltimore", "Ravens", 373),
  team("nfl-def-saints", "defense", "New Orleans", "Saints", 331),
  team("nfl-def-seahawks", "defense", "Seattle", "Seahawks", 411),
  team("nfl-def-steelers", "defense", "Pittsburgh", "Steelers", 300),
  team("nfl-def-texans", "defense", "Houston", "Texans", 295),
  team("nfl-def-titans", "defense", "Tennessee", "Titans", 314),
  team("nfl-def-vikings", "defense", "Minnesota", "Vikings", 423),
  // Alternate offensive playbooks (17)
  alternate("alt-off-air-raid", "offense", "Air Raid", 327),
  alternate("alt-off-air-raid-classic", "offense", "Air Raid Classic", 373),
  alternate("alt-off-balanced", "offense", "Balanced", 359),
  alternate("alt-off-benkerts-dimes", "offense", "Benkert's Dimes", 264),
  alternate("alt-off-pistol", "offense", "Pistol", 368),
  alternate("alt-off-run-and-shoot", "offense", "Run and Shoot", 228),
  alternate("alt-off-run-balanced", "offense", "Run Balanced", 419),
  alternate("alt-off-run-heavy", "offense", "Run Heavy", 354),
  alternate("alt-off-run-n-gun", "offense", "Run n Gun", 390),
  alternate("alt-off-shotgun", "offense", "Shotgun", 368),
  alternate("alt-off-shotgun-classic", "offense", "Shotgun Classic", 375),
  alternate("alt-off-shotgun-mix", "offense", "Shotgun Mix", 379),
  alternate("alt-off-singleback", "offense", "Singleback", 310),
  alternate("alt-off-spread", "offense", "Spread", 525),
  alternate("alt-off-spread-classic", "offense", "Spread Classic", 417),
  alternate("alt-off-two-back", "offense", "Two Back", 447),
  alternate("alt-off-west-coast", "offense", "West Coast", 414),
  // Alternate defensive playbooks (5)
  alternate("alt-def-3-4", "defense", "3-4", 208),
  alternate("alt-def-4-3", "defense", "4-3", 205),
  alternate("alt-def-46", "defense", "46", 189),
  alternate("alt-def-cover-2", "defense", "Cover 2", 157),
  alternate("alt-def-multiple-d", "defense", "Multiple D", 297),
];

export const INVENTORY_META = {
  source: "Civil.GG public playbook database (https://www.civil.gg/playbooks/madden)",
  crawledAt: "2026-10-06",
  note: "Counts are the source's published totals. 'Loaded' means this site has formation data for the book; it never claims verified mappings (D128).",
} as const;
